### ISSUE TITLE
How did you add Google Analytics?

### ISSUE THREAD

**Issue by pottekkat** [menkotoglou/personal-website#7]
I was using this theme and I came across your comment here: https://github.com/adityatelange/hugo-PaperMod/issues/178

I am not able to get GA to work. I am using GA 4 and I have copied my tracking ID and added it to the `config.yaml` file. Even though this snippet `{{- template "_internal/google_analytics.html" . }} is present in `themes/PaperMod/layouts/partials/head.html`, I have added it to `layouts/partials/header.html`as you have done here. Still it does not work. 

Do you know what the issue is? Here is my repo: https://github.com/navendu-pottekkat/navendu-pottekkat.github.io

PS: 😅  I haven't used Hugo or GA before, total noob when it comes to this.

**Comment by menkotoglou** [comment]
This comment was resolved by email communication with @navendu-pottekkat, so it can be closed.

**Comment by pottekkat** [comment]
Thank you @menkotoglou
